# Generated by Django 6.0 on 2026-01-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='paikey',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
