# Generated by Django 6.0 on 2026-01-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='periodicity_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='minutes', max_length=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='periodicity_value',
            field=models.IntegerField(default=5),
        ),
    ]
