# Generated by Django 6.0 on 2026-01-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='end_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='agent',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
