# Generated by Django 6.0 on 2026-01-01 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(editable=False, max_length=20, unique=True)),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('working', 'Working'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('start_time', models.TimeField(default='08:00')),
                ('end_time', models.TimeField(default='20:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='core.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
